test:
	g++ -o test test.cpp L1cache.cpp Mem.cpp

quick:
	g++ -o quicksort quicksort.cpp L1cache.cpp Mem.cpp

merge:
	g++ -o mergesort mergesort.cpp L1cache.cpp Mem.cpp

clean:
	rm -f test quicksort mergesort
